[tox]
envlist=py{39,310,311,312,313,py3},flake8
skip_missing_interpreters = true

[testenv]
setenv = PYTHONPATH = {toxinidir}:{toxinidir}/pythainlp
#commands = python3 -m unittest discover
changedir = tests
commands = discover
deps = discover
;  If you want to install the package with dependencies for testing:
; deps =
;     .[compact]
;     discover

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 pythainlp
