{% set version = "2.0.8" %}

package:
  name: pythainlp
  version: {{ version }}

source:
  path: ../
#source:
#  git_url: https://github.com/PyThaiNLP/pythainlp.git
#  git_tag: {{ version }}

{% set export = "export" %}  # [not win]
{% set export = "set" %}     # [win]


build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - nltk
    - future
    - six
    - dill
    - pytz
    - tqdm
    - requests
    - tinydb
    - python-marisa-trie
  run:
    - python


test:
  imports:
    - pythainlp

about:
  home: https://github.com/PyThaiNLP/pythainlp
  license: Apache License 2.0
  summary: 'Thai Natural Language Processing in Python.'

extra:
  recipe-maintainers:
    - pythainlp
