# SPDX-FileCopyrightText: 2026 PyThaiNLP Project
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileType: SOURCE

# Deploy documentation to https://pythainlp.org/docs/

name: Deploy dev docs
on:
  push:
    branches:
    - dev
    paths:
      - ".github/workflows/deploy-docs.yml"
      - "build_tools/**"
      - "docs/**"
      - "pythainlp/**"
      - "Makefile"
      - "pyproject.toml"
  workflow_dispatch: {}
    
jobs:
  deploy-docs:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - name: Install build tools and doc build tools
      run: pip install --upgrade pip
    - name: Install PyThaiNLP
      run: pip install ".[docs]"
    - name: Build sphinx documentation
      run: |
        cd docs && make html
        cd ..
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./docs/_build/html
        external_repository: PyThaiNLP/dev-docs
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
